<a href="https://colab.research.google.com/github/bharathjg/BTechProject-AttendanceSystem/blob/main/encoding_and_attendance_marking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
number_of_students = 4
name_matrix = ["Anuroop","kunju","midhun","Ramdas"]
#attendance_matrix = np.empty([number_of_students,7,5])
attendance_matrix_test = np.zeros([number_of_students,1])

-------------
#PROJECT NAME : FINAL REPO (previously named copy of Rebuild Main Dataset)
### AIM : TO CREATE THE FINAL REPOSITORY PROJECT    
-------------

## REPORT  
> THE PEOPLE WHO ARE AVAILABLE IN THE IMAGE HAS BEEN OBTAINED IN THE PICKLE FORMAT  
> THE UPDATED CODE HAS BEEN UPDATED IN THE CLOUD.  
> NEXT, WE NEED TO CHECK FOR AN IMAGE CONTAINING MULTIPLE PERSONNEL  
> THIS COPY WAS MADE TO RUN WITH THE BIGASS DATASET  
> FACED A SMALL PROBLEM. THE GPU IS RUNNING OUT OF MEMORY. SO, WE NEED A SMALLER TRAINING SET  
> THE SMALL DATASET HAS BEEN MADE. IT GOES BY THE NAME OF CUT_DATASET    
> CODE TO TAKE THE ATTENDANCE FOR AN HOUR IE FOR ONE IMAGE HAS BEEN COMPLETED  
>

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
## PREVIOUSLY ON  
1. Created a smalldataset and observed the working of pickle


## NEXT
1. Find a way to append pickle                                                  : DONE  
2. Write code to create pickle for large dataset
3. Show a small demonstration of the whole thing
4. Now, attempting to change the structure of the pyimagesearch guy and make it output 256 layes  
5. Appending the pickle in a loop until everyone's image's vector is in it

-------------
## AIM : import the cuda compatible dlib
note : To speed up the process using the gpu  
status : stable  
Project description : DLib is the library that contains the core classification network around which this project is built.   
Mission control : GO
-------------


In [ ]:
!git clone https://github.com/davisking/dlib.git
!cd dlib
!mkdir build
!cd build
!cmake .. -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
!cmake --build .
!cd ..
!python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA

Cloning into 'dlib'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 48171 (delta 1), reused 5 (delta 1), pack-reused 48162
Receiving objects: 100% (48171/48171), 22.81 MiB | 17.33 MiB/s, done.
Resolving deltas: 100% (33988/33988), done.
CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Error: could not load cache
python3: can't open file 'setup.py': [Errno 2] No such file or directory


-------------  
## AIM                 : To Install the Libraries
Note             : openCV,face_recognition, imutils, tree  
Status           : stable  
Project Description : The list of libraries used are
> XlsxWriter : This is the library used to finally write the output as an xlsx file.   
> openCV : Used for image manipulations and transformations.  
> face_recognition : The library developed by <insert name> to work around the dlib framework.  
> pickle_mixin : The library used for pickling.  
> imutils  : The package that makes image processing with openCV, matplot.lib and python easier.
Mission Control : GO
-------------

In [ ]:
!pip install XlsxWriter

     |████████████████████████████████| 143kB 6.6MB/s 


In [ ]:
!pip install opencv-contrib-python
!pip install face_recognition
!pip install imutils
!sudo apt install tree
!pip install pickle-mixin

     |████████████████████████████████| 100.2MB 31kB/s 
  Created wheel for face-recognition-models: filename=face_recognition_models-0.3.0-py2.py3-none-any.whl size=100566172 sha256=727cc58e6515c17f73456440098338fc1a90e63b6793bcf46c5dba1ed0004d0a
  Stored in directory: /root/.cache/pip/wheels/d2/99/18/59c6c8f01e39810415c0e63f5bede7d83dfb0ffc039865465f
Successfully built face-recognition-models
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-440
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  tree
0 upgraded, 1 newly installed, 0 to remove and 33 not upgraded.
Need to get 40.7 kB of archives.
After this operation, 105 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 tree amd64 1.7.0-5 [40.7 kB]
Fetched 40.7 kB in 0s (850 kB/s)
debconf: unable to initia

-------------
## AIM                 : Importing Libraries
##### Note             : plt,mpimg,Image,os
##### Status           : Stable
Project Description :  
Following are the libraries and the functions used that belongs to them  
> matplotlib.pyplot : <insert functions>  
> matplotlib.image : <insert the used functions>  
> Image as part of PIL :  
> Pickle :  
> numpy :  
> xlsxwriter :  
##### Mission control  : GO
-------------

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from PIL import Image
import os
import pickle
import numpy as np
import xlsxwriter

-------------
## AIM                 : Mounting The Google Drive
##### Note             : Mount vrsreeganesh@gmail.com
##### Status           : Stable
##### Mission control  : GO
-------------

In [ ]:
#mounting the google drive
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


-------------
## AIM                 : Copying the Main Zip File
##### Note             : Zip file contains code and data
##### Status           : Stable
Project Description : The zip file which is about to be copied contains the data from the pyimagesearch.com and associated files.
##### Mission control  : GO
-------------

In [ ]:
# Subsection A
# Note : copying the zip file
!cp /content/drive/My\ Drive/face-recognition-opencv.zip /content/

In [ ]:
# Subsection B
# Note : unzipping the file
!unzip face-recognition-opencv.zip

Archive:  face-recognition-opencv.zip
   creating: face-recognition-opencv/
   creating: face-recognition-opencv/dataset/
   creating: face-recognition-opencv/dataset/alan_grant/
  inflating: face-recognition-opencv/dataset/alan_grant/00000000.jpg  
  inflating: face-recognition-opencv/dataset/alan_grant/00000002.jpg  
 extracting: face-recognition-opencv/dataset/alan_grant/00000004.png  
  inflating: face-recognition-opencv/dataset/alan_grant/00000005.jpg  
  inflating: face-recognition-opencv/dataset/alan_grant/00000006.jpg  
 extracting: face-recognition-opencv/dataset/alan_grant/00000009.png  
  inflating: face-recognition-opencv/dataset/alan_grant/00000015.JPG  
  inflating: face-recognition-opencv/dataset/alan_grant/00000017.jpg  
  inflating: face-recognition-opencv/dataset/alan_grant/00000021.jpg  
  inflating: face-recognition-opencv/dataset/alan_grant/00000022.jpg  
  inflating: face-recognition-opencv/dataset/alan_grant/00000023.jpg  
  inflating: face-recognition-opencv/dat

In [ ]:
# Subsection       : B1
# Aim              : To import the updated files (encoded and rec) from drive
# Note             : Hasn't been updated btw in the drive side btw. (update cheythittundu)
# Status           : complete
# Mission control  : GO

!pwd
!mkdir actual_file #creating a directory to store the tbu code
!cp /content/drive/My\ Drive/dataset_local/encode_faces.py /content/actual_file
!cp /content/drive/My\ Drive/dataset_local/recognize_faces_image.py /content/actual_file

/content


In [ ]:
# Subsection : C
# Note : to enter the directory
%cd /content/face-recognition-opencv

/content/face-recognition-opencv


In [ ]:

# Subsection : D
# Note : To find the path
!pwd

/content/face-recognition-opencv


-------------
## AIM                 : Transfer cut dataset
##### Note             : This dataset contains amal, anuroop, kunju, midhun, ramdas  
##### Status           : Stable
Project Description :  The dataset that contains that of the students from the class are copied from the drive.
##### Mission control  : GO
-------------

In [ ]:
# don't run this until you want the datset local in the live dataset
!cp -avr /content/drive/My\ Drive/dataset_local/cut_dataset /content/face-recognition-opencv/dataset/

'/content/drive/My Drive/dataset_local/cut_dataset' -> '/content/face-recognition-opencv/dataset/cut_dataset'
'/content/drive/My Drive/dataset_local/cut_dataset/midhun' -> '/content/face-recognition-opencv/dataset/cut_dataset/midhun'
'/content/drive/My Drive/dataset_local/cut_dataset/midhun/20200205_124803 100.jpg' -> '/content/face-recognition-opencv/dataset/cut_dataset/midhun/20200205_124803 100.jpg'
'/content/drive/My Drive/dataset_local/cut_dataset/midhun/20200205_124803 073.jpg' -> '/content/face-recognition-opencv/dataset/cut_dataset/midhun/20200205_124803 073.jpg'
'/content/drive/My Drive/dataset_local/cut_dataset/midhun/20200205_124803 028.jpg' -> '/content/face-recognition-opencv/dataset/cut_dataset/midhun/20200205_124803 028.jpg'
'/content/drive/My Drive/dataset_local/cut_dataset/midhun/20200205_124803 064.jpg' -> '/content/face-recognition-opencv/dataset/cut_dataset/midhun/20200205_124803 064.jpg'
'/content/drive/My Drive/dataset_local/cut_dataset/midhun/20200205_124803 082.

-------------
## Aim                 : Copying The Correct Scripts From The Drive
##### Note             :
##### Status           : Stable
Project Description : The scripts we use are the ones that have been tweaked from the pyimagesearch.com's zip file. The tweaked files are in the drive. Here, what we do is we delete the file we obtained from unzipping the file and we replace it with our tweaked files.
##### Mission control  : GO
-------------

In [ ]:
# Subsection       : A-
# Aim              : updating the encoding script
# Note             : The old file is deleted and the updated is replaced. Bot have the same filename
# Status           : complete
# Mission control  : GO

!rm /content/face-recognition-opencv/encode_faces.py
!rm /content/face-recognition-opencv/recognize_faces_image.py

!cp /content/actual_file/encode_faces.py /content/face-recognition-opencv/
!cp /content/actual_file/recognize_faces_image.py /content/face-recognition-opencv/

In this segment, we're gonna run those script folder after folder. We're gonna test the loop here.

## AIM : Copying the amar_dataset to the live dataset  
Note : This dataset contains the photos of students from our class. About 13 in number

In [ ]:
# we gonna unzip the zip file that contains the amar_dataset
!mkdir /content/face-recognition-opencv/dataset/amar_dataset
!unzip /content/drive/My\ Drive/dataset_local/amar_dataset/amar.zip -d /content/face-recognition-opencv/dataset/amar_dataset/

Archive:  /content/drive/My Drive/dataset_local/amar_dataset/amar.zip
   creating: /content/face-recognition-opencv/dataset/amar_dataset/Bharath/
   creating: /content/face-recognition-opencv/dataset/amar_dataset/Amal_Mohan/
  inflating: /content/face-recognition-opencv/dataset/amar_dataset/Shivatheertha/VID-20200409-WA0068_022.jpg  
  inflating: /content/face-recognition-opencv/dataset/amar_dataset/Shivatheertha/VID-20200409-WA0068_027.jpg  
  inflating: /content/face-recognition-opencv/dataset/amar_dataset/Shivatheertha/VID-20200409-WA0068_017.jpg  
  inflating: /content/face-recognition-opencv/dataset/amar_dataset/Shivatheertha/VID-20200409-WA0068_042.jpg  
  inflating: /content/face-recognition-opencv/dataset/amar_dataset/Shivatheertha/VID-20200409-WA0068_025.jpg  
  inflating: /content/face-recognition-opencv/dataset/amar_dataset/Shivatheertha/VID-20200409-WA0068_019.jpg  
  inflating: /content/face-recognition-opencv/dataset/amar_dataset/Shivatheertha/VID-20200409-WA0068_040.jpg 

## AIM : Learnign The Encodings for the Cut_dataset

In [ ]:
# deleting any preexisting encodings_new.pickle
!rm encodings_new.pickle

rm: cannot remove 'encodings_new.pickle': No such file or directory


In [ ]:
# we're removing amal's folder cause it's causing some problems.
!rm -r /content/face-recognition-opencv/dataset/cut_dataset/Amal

In [ ]:
# Subsection       : A-3
# Aim              : Training on the dataset containing Anuroop, kunju, midhun, Ramdas
# Note             : running the encode_faces file.
# Status           : testing
# Mission control  : If running to observe pickle on bigass dataset, GO

!python /content/face-recognition-opencv/encode_faces.py --dataset /content/face-recognition-opencv/dataset/cut_dataset --encodings encodings_new.pickle

[INFO] quantifying faces...
[INFO] processing image 1/46
[INFO] processing image 2/46
[INFO] processing image 3/46
[INFO] processing image 4/46
[INFO] processing image 5/46
[INFO] processing image 6/46
[INFO] processing image 7/46
[INFO] processing image 8/46
[INFO] processing image 9/46
[INFO] processing image 10/46
[INFO] processing image 11/46
[INFO] processing image 12/46
[INFO] processing image 13/46
[INFO] processing image 14/46
[INFO] processing image 15/46
[INFO] processing image 16/46
[INFO] processing image 17/46
[INFO] processing image 18/46
[INFO] processing image 19/46
[INFO] processing image 20/46
[INFO] processing image 21/46
[INFO] processing image 22/46
[INFO] processing image 23/46
[INFO] processing image 24/46
[INFO] processing image 25/46
[INFO] processing image 26/46
[INFO] processing image 27/46
[INFO] processing image 28/46
[INFO] processing image 29/46
[INFO] processing image 30/46
[INFO] processing image 31/46
[INFO] processing image 32/46
[INFO] processing ima

In [ ]:
# loading the pickle and find the kind of data is input in

pickle_in = open("/content/face-recognition-opencv/encodings_new.pickle","rb")
samp_1 = pickle.load(pickle_in)
pickle_in.close()

print("Class of the dumped thing")
print(type(samp_1))


Class of the dumped thing
<class 'dict'>


## AIM : LEARNING THE ENCODINGS FOR THE AMAR_DATASET  
> The encodings learned are encodings_new.pickle  
> The dataset used is cut_dataset

In [ ]:
# deleting any preexisting encodings_new.pickle
!rm encodings_new.pickle

rm: cannot remove 'encodings_new.pickle': No such file or directory


In [ ]:
# we're removing amal's folder cause it's causing some problems.
!rm -r /content/face-recognition-opencv/dataset/amar_dataset/Amal_Mohan
!rm -r /content/face-recognition-opencv/dataset/amar_dataset/Bharath

In [ ]:
# This piece of code is just to check if we are able to get the path to all the folders.

# create a list containing the path to all subfolders
path_list = [x[0] for x in os.walk("/content/face-recognition-opencv/dataset/amar_dataset/")][1:]
print("The following is the path to all subfolders")
print(path_list)

The following is the path to all subfolders
['/content/face-recognition-opencv/dataset/amar_dataset/Oscar', '/content/face-recognition-opencv/dataset/amar_dataset/Athira', '/content/face-recognition-opencv/dataset/amar_dataset/Anuroop', '/content/face-recognition-opencv/dataset/amar_dataset/Adarsh', '/content/face-recognition-opencv/dataset/amar_dataset/Sruthi', '/content/face-recognition-opencv/dataset/amar_dataset/Ramdas', '/content/face-recognition-opencv/dataset/amar_dataset/Akshay_PL', '/content/face-recognition-opencv/dataset/amar_dataset/Naveen', '/content/face-recognition-opencv/dataset/amar_dataset/Navami', '/content/face-recognition-opencv/dataset/amar_dataset/Amal_Vincent', '/content/face-recognition-opencv/dataset/amar_dataset/Midhun', '/content/face-recognition-opencv/dataset/amar_dataset/Shivatheertha', '/content/face-recognition-opencv/dataset/amar_dataset/Uma_U']


In [ ]:
# create a list containing the path to all subfolders
path_list = [x[0] for x in os.walk("/content/face-recognition-opencv/dataset/amar_dataset/")][1:]
print("The following is the path to all subfolders")
print(path_list)

# defining an empty list
list_encodings = []
list_names = []

i = 0
while i<len(path_list): # looping over all the folders in the dataset directory

    # root folder contains the path for an individual folder
    root_folder = path_list[i]

    # the part where we run the script on the dataset. This guy produces encodings_new.pickle
    !python /content/face-recognition-opencv/encode_faces.py --dataset $root_folder --encodings encodings_new.pickle

    # we open the pickle file
    pickle_in = open("/content/face-recognition-opencv/encodings_new.pickle","rb")
    samp_1 = pickle.load(pickle_in)
    pickle_in.close()

    # deleting the file since it shouldn't cause a problem for
    !rm /content/face-recognition-opencv/encodings_new.pickle

    # appending the list
    list_encodings.extend(samp_1['encodings'])
    list_names.extend(samp_1['names'])

    #printing the status
    print("The class of samp_1['encodings']")
    print(type(samp_1['encodings']))

    print("The number of encodings in the pickle")
    print(len(samp_1['encodings']))

    print("The number of encodings in the list_encodings")
    print(len(list_encodings))

    # updating the i
    i+=1

# printing the final length
print("The length of list_encodings")
print(len(list_encodings))

print("The length of list_names")
print(len(list_names))

The following is the path to all subfolders
['/content/face-recognition-opencv/dataset/amar_dataset/Oscar', '/content/face-recognition-opencv/dataset/amar_dataset/Athira', '/content/face-recognition-opencv/dataset/amar_dataset/Anuroop', '/content/face-recognition-opencv/dataset/amar_dataset/Adarsh', '/content/face-recognition-opencv/dataset/amar_dataset/Sruthi', '/content/face-recognition-opencv/dataset/amar_dataset/Ramdas', '/content/face-recognition-opencv/dataset/amar_dataset/Akshay_PL', '/content/face-recognition-opencv/dataset/amar_dataset/Naveen', '/content/face-recognition-opencv/dataset/amar_dataset/Navami', '/content/face-recognition-opencv/dataset/amar_dataset/Amal_Vincent', '/content/face-recognition-opencv/dataset/amar_dataset/Midhun', '/content/face-recognition-opencv/dataset/amar_dataset/Shivatheertha', '/content/face-recognition-opencv/dataset/amar_dataset/Uma_U']
[INFO] quantifying faces...
[INFO] processing image 1/71
[INFO] processing image 2/71
[INFO] processing imag

In [ ]:
# Listing All the encodings in the directory
!ls -lh encodings*

-rw-r--r-- 1 root root 235K May 29  2018 encodings.pickle


In [ ]:
# The encodings and names are combined and made into a pickle here
# pickle file: aggregatepickle.pkl
# database
db = {}
db['encodings'] = list_encodings
db['names'] = list_names

#opening a pickle file to write
dbfile = open('/content/face-recognition-opencv/aggregatepickle.pkl','wb')
pickle.dump(db,dbfile)
dbfile.close

print(type(db))

<class 'dict'>


In [ ]:
#Reading the aggregate pickle file
dbfile = open('/content/face-recognition-opencv/aggregatepickle.pkl','rb')
db_read = pickle.load(dbfile)
dbfile.close()

print("The length of db_read['encodings']")
print(len(db_read['encodings']))


The length of db_read['encodings']
1290


## AIM : To Find The Names In The Encodings

In [ ]:
def unique(list1):

    # intilize a null list
    unique_list = []

    # traverse for all elements
    for x in list1:
        # check if exists in unique_list or not
        if x not in unique_list:
            unique_list.append(x)
    # print list
    for x in unique_list:
        print(x)

unique(list_names)

Oscar
Athira
Anuroop
Adarsh
Sruthi
Ramdas
Akshay_PL
Naveen
Navami
Amal_Vincent
Midhun
Shivatheertha
Uma_U


## AIM : Creating A Loop for The Recognizing Images

In [ ]:
# copying the test_folder dataset
!cp -avr /content/drive/My\ Drive/dataset_local/test_image_folder /content/face-recognition-opencv/dataset/

'/content/drive/My Drive/dataset_local/test_image_folder' -> '/content/face-recognition-opencv/dataset/test_image_folder'
'/content/drive/My Drive/dataset_local/test_image_folder/test_image_2.jpg' -> '/content/face-recognition-opencv/dataset/test_image_folder/test_image_2.jpg'
'/content/drive/My Drive/dataset_local/test_image_folder/test_image_3.jpg' -> '/content/face-recognition-opencv/dataset/test_image_folder/test_image_3.jpg'
'/content/drive/My Drive/dataset_local/test_image_folder/test_image_1.jpg' -> '/content/face-recognition-opencv/dataset/test_image_folder/test_image_1.jpg'
'/content/drive/My Drive/dataset_local/test_image_folder/test_image_0.jpg' -> '/content/face-recognition-opencv/dataset/test_image_folder/test_image_0.jpg'
'/content/drive/My Drive/dataset_local/test_image_folder/vincent.jpg' -> '/content/face-recognition-opencv/dataset/test_image_folder/vincent.jpg'


In [ ]:
# create a list containing the path to all subfolders
import glob

In [ ]:
# test_paths contain the list of complete paths to all files
test_paths = glob.glob("/content/face-recognition-opencv/dataset/test_image_folder/*.jpg")
print(test_paths)

['/content/face-recognition-opencv/dataset/test_image_folder/test_image_3.jpg', '/content/face-recognition-opencv/dataset/test_image_folder/test_image_2.jpg', '/content/face-recognition-opencv/dataset/test_image_folder/test_image_0.jpg', '/content/face-recognition-opencv/dataset/test_image_folder/vincent.jpg', '/content/face-recognition-opencv/dataset/test_image_folder/test_image_1.jpg']


In [ ]:
# creating attendance matrix
name_matrix = ["Naveen", "Sruthi", "Anuroop", "Amal_Vincent", "Navami", "Uma_U", "Midhun", "Shivatheertha", "Adarsh", "Athira", "Oscar", "Akshay_PL", "Ramdas"]
attendance_matrix_test = np.zeros([len(name_matrix),len(test_paths)])

print("The shape of attendance_matrix_test =", attendance_matrix_test.shape)
print("This is the attendance_matrix_test")
print(attendance_matrix_test)

The shape of attendance_matrix_test = (13, 5)
This is the attendance_matrix_test
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# AIM: Recognising part

Here, we find the encoding for a single image

In [ ]:
# USAGE
# python recognize_faces_image.py --encodings encodings.pickle --image examples/example_01.png


# import the necessary packages
import face_recognition
import pickle
import cv2
import os

# load the input image and convert it from BGR to RGB
image = cv2.imread('/content/face-recognition-opencv/dataset/test_image_folder/test_image_3.jpg')
rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# detect the (x, y)-coordinates of the bounding boxes corresponding
# to each face in the input image, then compute the facial embeddings
# for each face
print("[INFO] recognizing faces...")
boxes = face_recognition.face_locations(rgb,
    model="cnn")
encodings = face_recognition.face_encodings(rgb, boxes) # this is the guy that takes the encodings

# the output will be a list.
print(
    "The encoding of the image is ",
    encodings[1]
)

number_of_people_in_image = len(encodings)
print(
    "The number of people in the image is ",
    number_of_people_in_image
)

[INFO] recognizing faces...
The encoding of the image is  [-1.20307729e-01  1.18554533e-01  9.40645188e-02 -1.92211792e-02
 -7.91855529e-02 -3.61851901e-02  1.35016814e-02  1.98641792e-02
  1.46640182e-01 -2.61861086e-02  1.77343935e-01 -2.37914622e-02
 -2.01898620e-01 -1.39666155e-01  2.98371911e-02  1.32413849e-01
 -8.72153938e-02 -1.80034071e-01 -2.22388767e-02 -6.57090992e-02
  2.14263797e-02  2.17185952e-02  5.30094653e-03  6.53399378e-02
 -1.38054609e-01 -3.15690577e-01 -5.75329773e-02 -1.86954260e-01
  3.12569812e-02 -1.68628797e-01 -5.74095100e-02  6.99947476e-02
 -1.41596243e-01 -6.33031130e-02 -2.26126090e-02  1.15321763e-01
  1.63331628e-04 -8.33646134e-02  1.68369502e-01  5.57099730e-02
 -1.24932535e-01 -1.24682888e-01 -8.02362710e-03  3.31975281e-01
  1.67372674e-01 -1.91462040e-03  6.54978156e-02  2.08953507e-02
  5.44446334e-02 -2.03163326e-01  6.67375326e-02  1.13851875e-01
  1.65222198e-01  5.64715900e-02  4.57051247e-02 -1.30480081e-01
  3.76441851e-02 -5.61153740e-02

Here, we compare the encoding of a single photo with every other encoding in the database

In [ ]:
# to compare the encoding of the people in the image with our database

#first, we need to load our database
# we'll be using the aggregatepickle file
print("[INFO] loading encodings...")
dbfile = open('/content/face-recognition-opencv/aggregatepickle.pkl','rb')
db_read = pickle.load(dbfile) # db_read file contains the dictionary
dbfile.close()

database_encodings = db_read["encodings"] # note that database_encodings is a list
# there are 1290 encodings
print(
    "The number of encodings in the pickle",
    len(database_encodings)
)

#first find the distance between the database. Find the max. If the max is more than a threshold,
# find the index and assign the name.

distance_vector = np.empty(len(database_encodings), dtype = np.float32)

i = 0
while i<len(database_encodings):
    distance_vector[i] = np.sqrt(np.sum(np.square(encodings[0] - database_encodings[i])))
    i+=1

print(
    "The maximum value in the distance_vector is ",
    np.max(distance_vector)
)

print(
    "The minimum value in the distance_vector is ",
    np.min(distance_vector)
)


[INFO] loading encodings...
The number of encodings in the pickle 1290
The maximum value in the distance_vector is  0.8990908
The minimum value in the distance_vector is  0.40332505


Here, we try to find the appropriate threshold.  
We took the image of midhun and compared it with the database and found the min, max and mean distances with the rest of the images in the cluster

In [ ]:
# copying midhuns image from the drive to our thingy
!cp /content/drive/My\ Drive/dataset_local/test_image_folder/midhun_1.jpg /content/face-recognition-opencv/dataset/test_image_folder/

In [ ]:
# this cell is to decide on a threshold value


# import the necessary packages
import face_recognition
import pickle
import cv2
import os

# load the input image and convert it from BGR to RGB
image = cv2.imread('/content/face-recognition-opencv/dataset/test_image_folder/midhun_1.jpg')
rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# detect the (x, y)-coordinates of the bounding boxes corresponding
# to each face in the input image, then compute the facial embeddings
# for each face
print("[INFO] recognizing faces...")
boxes = face_recognition.face_locations(rgb,
    model="cnn")
encodings = face_recognition.face_encodings(rgb, boxes) # this is the guy that takes the encodings
 #------------------------------------------------------------------------------

# we shall be doing it with midhun

indice_list = [i for i, n in enumerate(db_read["names"]) if n == 'Midhun'] # List comprehension

distance_vector_midhun = np.empty(len(indice_list), dtype=np.float32)

i = 0
while i<len(indice_list):

    distance_vector_midhun[i] = np.sqrt(np.sum(np.square(db_read["encodings"][indice_list[i]] - encodings)))
    i += 1

print(
    "The maximum value in distance_vector_midhun is ",
    np.max(distance_vector_midhun)
)

print(
    "The minimum value in distance_vector_midhun is ",
    np.min(distance_vector_midhun)
)

print(
    "The mean value in distance_vector_midhun is ",
    np.mean(distance_vector_midhun)
)



[INFO] recognizing faces...
The maximum value in distance_vector_midhun is  0.7393695
The minimum value in distance_vector_midhun is  0.40332505
The mean value in distance_vector_midhun is  0.5898415


Uptil here was done last night

In [ ]:
# defining an empty list
list_encodings = []
list_names = []

# initialing an empty attendance matrix
attendance_matrix_test = np.zeros([len(name_matrix),len(test_paths)])

i = 0
while i<len(test_paths): # looping over all the folders in the dataset directory

    # root folder contains the path for an individual folder
    root_folder = test_paths[i]
    print("This is the image we're processing in this iteration")
    print(root_folder)

    # the part where we run the script on the dataset.
    !python /content/drive/My\ Drive/dataset_local/recognise_faces_test_1.py --encodings /content/face-recognition-opencv/aggregatepickle.pkl --image $root_folder

    # we open the pickle file
    pickle_in = open("/content/face-recognition-opencv/names_parrot.pickle","rb")
    samp_2 = pickle.load(pickle_in)
    pickle_in.close()

    # deleting the file since it shouldn't be empty the next time
    !rm /content/face-recognition-opencv/names_parrot.pickle

    # with each photo, you need to append attendance

    k = 0
    while k<len(samp_2):
        j = 0
        while j<len(name_matrix):
            if name_matrix[j]==samp_2[k]:
                attendance_matrix_test[j,i]=1
            j+=1
        k+=1


    # printing the attendance_matrix_test
    print("This is the attendance_matrix_test")
    print(attendance_matrix_test)

    # updating the i
    i+=1


This is the image we're processing in this iteration
/content/face-recognition-opencv/dataset/test_image_folder/test_image_3.jpg
[INFO] loading encodings...
[INFO] recognizing faces...
<class 'list'>
['Ramdas', 'Midhun']
THE LIST NAMES HAS BEEN SUCCESSFULLY PICKLED
This is the attendance_matrix_test
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
This is the image we're processing in this iteration
/content/face-recognition-opencv/dataset/test_image_folder/test_image_2.jpg
[INFO] loading encodings...
[INFO] recognizing faces...
<class 'list'>
['Ramdas', 'Anuroop']
THE LIST NAMES HAS BEEN SUCCESSFULLY PICKLED
This is the attendance_matrix_test
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]


## AIM : CREATING THE ATTENDANCE MATRICES  
> One matrix containing the names  
> The other matrix containing the attendance

In [ ]:
number_of_students = 4
name_matrix = ["Anuroop","kunju","midhun","Ramdas"]
#attendance_matrix = np.empty([number_of_students,7,5])
attendance_matrix_test = np.zeros([number_of_students,1])

## AIM : TAKING ATTENDANCE FOR AN HOUR  
> Running recognize_faces on multiple images and updating the attendance_matrix correspondingly  

In [ ]:
#running the recognize_faces with 5 images (since 5 images an hour)
# for now, we do with one image
# since we already have a pickled list, we're just gonna start comparing that

i=0
while i<len(samp_2): # we consider one name from the samp_2 pickle and search the database
  j=0
  while j<len(name_matrix):
    if name_matrix[j]==samp_2[i]: #if the name is in the database,
      attendance_matrix_test[j]=1 # we mark the attendance.
    j+=1
  i+=1


In [ ]:
print(attendance_matrix_test)

[[0.]
 [0.]
 [1.]
 [1.]]


## AIM : TO LOOP THE RECOGNIZE SCRIPT OVER THE IMAGES IN A FOLDER  
> This is assuming that we're taking only one photo an hour

> Finding the number of files

In [ ]:
import os

list = os.listdir('/content/drive/My Drive/dataset_local/test_image_folder')         # dir is your directory path
number_files = len(list)
print(" The number of files in the directory = ", number_files)

 The number of files in the directory =  4


> The script is run on an image under a loop  
> I intend to open the pickle, store the value to a matrix, delete the pickle and let the thing loop  
> Note that this scripting is for the cut_dataset

In [ ]:
attendance_matrix = np.zeros([4,4])

#name_string contains the command to recognise faces of an image in the string format
name_string = "python /content/drive/My\ Drive/dataset_local/recognise_faces_test_1.py --encodings encodings_new.pickle --image /content/drive/My\ Drive/dataset_local/test_image_folder/test_image_"
i=0


while i<number_files:                         # 'i' is to go through the images
  name_string = name_string + str(i) + '.jpg' #done so as to name the target image. read the whole of name_string
  print(name_string)                          # to check if we got the string right
  !$name_string                               # running the script to recognise faces
  # once that is done, we reset the name_string to the initial string since this is a loop
  name_string = "python /content/drive/My\ Drive/dataset_local/recognise_faces_test_1.py --encodings encodings_new.pickle --image /content/drive/My\ Drive/dataset_local/test_image_folder/test_image_"

  # samp_2 contains the pickle that is produced by the recognise faces
  print("enter pickle")
  pickle_in = open("/content/face-recognition-opencv/names_parrot.pickle","rb")
  samp_2 = pickle.load(pickle_in)
  pickle_in.close()
  print("Exit pickle ")

  # marking attendance
  print("Entered attendance part")

  k=0                               # variable to go through the recognized names
  while k<len(samp_2):
    j=0
    while j<len(name_matrix):       # j is used to go through the record
      if name_matrix[j]==samp_2[k]:
        attendance_matrix[j,i]+=1   # marking the attendance
      j+=1
    k+=1

  # the row values contain attendance corresponding to names
  # the column indicates the photo number
  print("i=",i)
  print("shape of attendance matrix",attendance_matrix.shape)
  print(attendance_matrix)

  !rm /content/face-recognition-opencv/names_parrot.pickle
  i+=1



python /content/drive/My\ Drive/dataset_local/recognise_faces_test_1.py --encodings encodings_new.pickle --image /content/drive/My\ Drive/dataset_local/test_image_folder/test_image_0.jpg
[INFO] loading encodings...
[INFO] recognizing faces...
<class 'list'>
['Ramdas', 'Anuroop']
THE LIST NAMES HAS BEEN SUCCESSFULLY PICKLED
enter pickle
Exit pickle 
Entered attendance part
i= 0
shape of attendance matrix (4, 4)
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
python /content/drive/My\ Drive/dataset_local/recognise_faces_test_1.py --encodings encodings_new.pickle --image /content/drive/My\ Drive/dataset_local/test_image_folder/test_image_1.jpg
[INFO] loading encodings...
[INFO] recognizing faces...
<class 'list'>
['Ramdas', 'midhun']
THE LIST NAMES HAS BEEN SUCCESSFULLY PICKLED
enter pickle
Exit pickle 
Entered attendance part
i= 1
shape of attendance matrix (4, 4)
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 1. 0. 0.]]
python /content/drive/My\ Drive/dataset_local/recog

stack overflow to write to an excel sheet
https://stackoverflow.com/questions/31909722/how-to-write-python-array-into-excel-spread-sheet

this should help in pickling the names list too   
https://stackoverflow.com/questions/25464295/how-to-pickle-a-list

## WRITING TO AN EXCEL FILE  

In [ ]:
!rm /content/array.xlsx

rm: cannot remove '/content/array.xlsx': No such file or directory


In [ ]:
workbook = xlsxwriter.Workbook("/content/array.xlsx")
worksheet = workbook.add_worksheet()

# the dimension of the names list is 1x4

col = 2 # starting column
row = 2 # starting row
i=0

# Name column ezhuthi edukkal
while i<len(name_matrix):
  worksheet.write(row+i,col,name_matrix[i])
  i+=1


row = 2 # starting row
col = 3 # starting column
i = 0

#printing is done column wise
while i < attendance_matrix.shape[0]:                       # i represents parsing through the row
  j = 0
  while j < attendance_matrix.shape[1]:                     # printing column first
    worksheet.write(row + i,col+j,attendance_matrix[i,j])
    j+=1

  i+=1

workbook.close()

# Checkpoint - Works well

## NOTE : HOW THE DIRECTORIES MUST BE  
> There must be a folder for an hour. Each such hour_folder must contain 5 photos.  
> The hour_folders must be named as hour_1, hour_2 and so on.  
> A day_folder must contain six hour_folder.  
> The day folder must be named as per the date. Preferably in dd_mm_yyyy  


In [ ]:
import os
print(os.path.splitext("/path/to/some/file.txt")[0])

/path/to/some/file


In [ ]:
# code to test moving through the libraries
from imutils import paths
import face_recognition
import argparse
import pickle
import cv2
import os

imagePaths = paths.list_images("/content/face-recognition-opencv/dataset/cut_dataset/Anuroop")
print(type(imagePaths))

<class 'generator'>


In [ ]:
def imlist(path):
    """
    The function imlist returns all the names of the files in
    the directory path supplied as argument to the function.
    """
    return [os.path.join(path, f) for f in os.listdir(path)]


In [ ]:
print(type(imlist("/content/face-recognition-opencv/dataset/cut_dataset/Anuroop")))

<class 'list'>


In [ ]:
print(len(imlist("/content/face-recognition-opencv/dataset/cut_dataset/Anuroop")))

11


> The following code needs to be edited so that this thing canloop over folders that contains folders. NOTE that this folder has not be edited

In [ ]:
attendance_matrix = np.zeros([4,4])
i=0
name_string = "python /content/drive/My\ Drive/dataset_local/recognise_faces_test_1.py --encodings encodings_new.pickle --image /content/drive/My\ Drive/dataset_local/test_image_folder/test_image_"
while i<number_files:
  name_string = name_string + str(i) + '.jpg'
  print(name_string)
  !$name_string
  name_string = "python /content/drive/My\ Drive/dataset_local/recognise_faces_test_1.py --encodings encodings_new.pickle --image /content/drive/My\ Drive/dataset_local/test_image_folder/test_image_"

  print("enter pickle")
  pickle_in = open("/content/face-recognition-opencv/names_parrot.pickle","rb")
  samp_2 = pickle.load(pickle_in)
  pickle_in.close()
  print("Exit pickle ")

  print("Entered attendance part")

  k=0
  while k<len(samp_2):
    j=0
    while j<len(name_matrix):
      if name_matrix[j]==samp_2[k]:
        attendance_matrix[j,i]+=1
      j+=1
    k+=1

  print("i=",i)
  print("shape of attendance matrix",attendance_matrix.shape)
  print(attendance_matrix)

  !rm /content/face-recognition-opencv/names_parrot.pickle
  i+=1

